"""
Database models for AI News Bot.

SQLModel models for persistent storage of articles, categories, and digests.
Supports multi-mission architecture with mission-scoped data.
"""

from datetime import date as DateType, datetime
from typing import Any, Optional

from sqlalchemy import Column
from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Field, Relationship, SQLModel, UniqueConstraint


class Mission(SQLModel, table=True):
    """Mission configuration (e.g., ai-news, video-games)."""

    __tablename__ = "missions"

    id: str = Field(primary_key=True, max_length=50)
    name: str = Field(max_length=100)
    description: str | None = Field(default=None, max_length=500)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Relationships
    categories: list["Category"] = Relationship(back_populates="mission")
    articles: list["Article"] = Relationship(back_populates="mission")
    daily_digests: list["DailyDigest"] = Relationship(back_populates="mission")
    weekly_digests: list["WeeklyDigest"] = Relationship(back_populates="mission")


class Category(SQLModel, table=True):
    """Dynamic category for articles, scoped by mission."""

    __tablename__ = "categories"
    __table_args__ = (UniqueConstraint("mission_id", "name", name="uq_category_mission_name"),)

    id: int | None = Field(default=None, primary_key=True)
    mission_id: str = Field(foreign_key="missions.id", max_length=50)
    name: str = Field(max_length=100)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Relationships
    mission: Mission = Relationship(back_populates="categories")
    articles: list["Article"] = Relationship(back_populates="category")


class Article(SQLModel, table=True):
    """News article collected from RSS feeds or web search."""

    __tablename__ = "articles"

    id: int | None = Field(default=None, primary_key=True)
    mission_id: str = Field(foreign_key="missions.id", max_length=50, index=True)
    category_id: int | None = Field(default=None, foreign_key="categories.id")
    daily_digest_id: int | None = Field(default=None, foreign_key="daily_digests.id")

    title: str = Field(max_length=500)
    url: str = Field(max_length=2000, unique=True)
    source: str = Field(max_length=100)
    description: str | None = Field(default=None, max_length=2000)
    pub_date: datetime | None = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Relationships
    mission: Mission = Relationship(back_populates="articles")
    category: Optional["Category"] = Relationship(back_populates="articles")
    daily_digest: Optional["DailyDigest"] = Relationship(back_populates="articles")


class DailyDigest(SQLModel, table=True):
    """Daily digest generated by Claude."""

    __tablename__ = "daily_digests"
    __table_args__ = (UniqueConstraint("mission_id", "date", name="uq_daily_digest_mission_date"),)

    id: int | None = Field(default=None, primary_key=True)
    mission_id: str = Field(foreign_key="missions.id", max_length=50, index=True)
    date: DateType = Field(index=True)
    content: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    posted_to_discord: bool = Field(default=False)

    # Relationships
    mission: Mission = Relationship(back_populates="daily_digests")
    articles: list[Article] = Relationship(back_populates="daily_digest")


class WeeklyDigest(SQLModel, table=True):
    """Weekly digest with analysis of trends."""

    __tablename__ = "weekly_digests"

    id: int | None = Field(default=None, primary_key=True)
    mission_id: str = Field(foreign_key="missions.id", max_length=50, index=True)
    week_start: DateType = Field(index=True)
    week_end: DateType
    params: dict[str, Any] | None = Field(default=None, sa_column=Column(JSON))
    content: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    is_standard: bool = Field(default=True)
    posted_to_discord: bool = Field(default=False)

    # Relationships
    mission: Mission = Relationship(back_populates="weekly_digests")
